# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Apie mus"
  url = "apie-mus"
  weight = 10

[[main]]
  name = "Naujienos"
  url = "#posts"
  weight = 20

[[main]]
  name = "Mūsų šunys"
  identifier = "musu-sunys"
  url = "musu-sunys"
  weight = 30

  [[main]]
  name = "Luna Lambert Goravan Kalnų Talismanas"
  parent = "musu-sunys"
  identifier = "musu-sunys-luna"
  url = "musu-sunys/luna/"

  [[main]]
  name = "Laira Lambert Goravan Kalnų Talismanas"
  parent = "musu-sunys"
  identifier = "musu-sunys-laira"
  url = "musu-sunys/laira/"

  [[main]]
  name = "Watson Tasmanska Elitte"
  parent = "musu-sunys"
  identifier = "musu-sunys-watson"
  url = "musu-sunys/watson/"

  [[main]]
  name = "Lela Raganos Šuo"
  parent = "musu-sunys"
  identifier = "musu-sunys-lela"
  url = "musu-sunys/lela/"

  [[main]]
  name = "Arkana Raganos Šuo"
  parent = "musu-sunys"
  identifier = "musu-sunys-arkana"
  url = "musu-sunys/arkana/"

[[main]]
  name = "Vados"
  url = "vados"
  weight = 40

  [[main]]
  name = "L vada"
  parent = "Vados"
  identifier = "vados-l-vada"
  url = "vados/l-vada/"

  [[main]]
  name = "A vada"
  parent = "Vados"
  identifier = "vados-a-vada"
  url = "vados/a-vada/"

  [[main]]
  name = "T vada"
  parent = "Vados"
  identifier = "vados-t-vada"
  url = "vados/t-vada/"

  [[main]]
  name = ".Planuojama vada"
  parent = "Vados"
  identifier = "vados-planuojama-vada"
  url = "vados/planuojama-vada/"

 [[main]]
  name = "In memorian"
  url = "in-memorian"
  weight = 50

 [[main]]
  name = "Lambert Tasmanska Elitte"
  parent = "In memorian"
  identifier = "in-memorian-lambert-tasmanska-elitte"
  url = "in-memorian/lambert-tasmanska-elitte/"

[[main]]
  name = "Kontaktai"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
